server:
  port: 8085
spring:        
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:../data/database2
    username: sa
    password: sa
    
    